version: '3.8'

services:
  # تطبيق INFINITY BOX الرئيسي
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: infinitybox-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017/infinitybox}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_here}
      - SESSION_SECRET=${SESSION_SECRET:-your_session_secret_here}
      - AGORA_APP_ID=${AGORA_APP_ID}
      - AGORA_APP_CERTIFICATE=${AGORA_APP_CERTIFICATE}
      - ENABLE_ANALYTICS=true
      - ENABLE_BACKUP=true
      - ENABLE_CACHE=true
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./backups:/app/backups
      - ./analytics:/app/analytics
      - ./logs:/app/logs
    networks:
      - app-network
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # قاعدة بيانات MongoDB
  mongo:
    image: mongo:6.0
    container_name: infinitybox-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password123}
      - MONGO_INITDB_DATABASE=infinitybox
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: unless-stopped

  # Redis للكاش (اختياري)
  redis:
    image: redis:7-alpine
    container_name: infinitybox-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge